export const data = [
  {
    id: 1,
    title: "Introducción a JavaScript",
    instructor: "John Doe",
    image: "https://th.bing.com/th/id/OIP.nudL-AIn-Eg7638lJRmlMQHaE8?rs=1&pid=ImgDetMain",
    price: 50,
    level: "Principiante",
    duration: "4 semanas",
    description: "Aprende los fundamentos de JavaScript, incluyendo variables, funciones, condicionales y bucles.",
  },
  {
    id: 2,
    title: "Desarrollo Web con React",
    instructor: "Jane Smith",
    image: "https://th.bing.com/th/id/OIP.uf5Wr4c5nlbGbTR0XyGUvQHaEO?rs=1&pid=ImgDetMain",
    price: 80,
    level: "Intermedio",
    duration: "6 semanas",
    description: "Domina React y construye aplicaciones web modernas utilizando componentes reutilizables y el enfoque de desarrollo basado en componentes.",
  },
  {
    id: 3,
    title: "Python para Ciencia de Datos",
    instructor: "Michael Johnson",
    image: "https://th.bing.com/th/id/R.ad0b5f894cd121b12d7097b610a216c6?rik=jIzfnPUPWvG3Zg&pid=ImgRaw&r=0",
    price: 70,
    level: "Avanzado",
    duration: "8 semanas",
    description: "Aprende Python desde cero y aplica tus conocimientos en análisis de datos, aprendizaje automático y visualización de datos.",
  },
  {
    id: 4,
    title: "Desarrollo de Aplicaciones Móviles con React Native",
    instructor: "Emily Rodriguez",
    image: "https://edteam-media.s3.amazonaws.com/courses/original/9cfa2a82-e1d9-4903-849f-b3d09804a703.png",
    price: 90,
    level: "Intermedio",
    duration: "10 semanas",
    description: "Crea aplicaciones móviles multiplataforma con React Native, utilizando JavaScript para desarrollar para iOS y Android.",
  },
  {
    id: 5,
    title: "Diseño de Interfaces de Usuario",
    instructor: "Alexis Thompson",
    image: "https://th.bing.com/th/id/R.40856b3c2436e3e24447df477edb85f2?rik=Iaw3dSgSjat7jA&pid=ImgRaw&r=0",
    price: 60,
    level: "Intermedio",
    duration: "6 semanas",
    description: "Aprende los principios de diseño de interfaces de usuario y cómo aplicarlos en el desarrollo web y móvil.",
  },
  {
    id: 6,
    title: "Java Fundamentals",
    instructor: "David Brown",
    image: "https://th.bing.com/th/id/R.8a3fb066568ba9bfddf9e8e10a4af196?rik=GAyeQ04HjU90Lw&pid=ImgRaw&r=0",
    price: 75,
    level: "Principiante",
    duration: "8 semanas",
    description: "Domina los fundamentos de Java, incluyendo clases, objetos, herencia, polimorfismo y manejo de excepciones.",
  },
  {
    id: 7,
    title: "Diseño de Bases de Datos Relacionales",
    instructor: "Samantha Green",
    image: "https://www.proscont.com/wp-content/uploads/2023/10/bases-datos.jpg",
    price: 65,
    level: "Intermedio",
    duration: "6 semanas",
    description: "Aprende a diseñar bases de datos relacionales eficientes utilizando SQL y modelado de datos.",
  },
  {
    id: 8,
    title: "Machine Learning con Python",
    instructor: "Daniel Johnson",
    image: "https://th.bing.com/th/id/R.d6deb3373ea09d17ec1765565e5370ef?rik=73d1ZzQ4PpuQMg&pid=ImgRaw&r=0",
    price: 85,
    level: "Avanzado",
    duration: "10 semanas",
    description: "Explora algoritmos de machine learning y técnicas de modelado predictivo utilizando la biblioteca scikit-learn de Python.",
  },
  {
    id: 9,
    title: "Desarrollo de Videojuegos con Unity",
    instructor: "Sophia Martinez",
    image: "https://th.bing.com/th/id/R.1ee26be7a9b7749f1a6a5ed989e5e70d?rik=HNcrCC2vsccLUA&pid=ImgRaw&r=0",
    price: 95,
    level: "Intermedio",
    duration: "12 semanas",
    description: "Crea tus propios videojuegos con Unity, desde la conceptualización hasta la implementación y distribución.",
  },
  {
    id: 10,
    title: "Desarrollo de Aplicaciones Android con Kotlin",
    instructor: "Ryan Clark",
    image: "https://th.bing.com/th/id/R.ad854d726e792152866211a25719f6c1?rik=BhpSVCfr3933ag&pid=ImgRaw&r=0",
    price: 90,
    level: "Intermedio",
    duration: "8 semanas",
    description: "Aprende Kotlin y desarrolla aplicaciones móviles para Android, aprovechando las características modernas del lenguaje.",
  },
  {
    id: 11,
    title: "Desarrollo de Aplicaciones iOS con Swift",
    instructor: "Isabella White",
    image: "https://th.bing.com/th/id/OIP.9qvEOLBQExKPGoGMZNgZxQHaHa?rs=1&pid=ImgDetMain",
    price: 90,
    level: "Intermedio",
    duration: "8 semanas",
    description: "Domina Swift y desarrolla aplicaciones para iOS, incluyendo iPhone, iPad y Apple Watch.",
  },
  {
    id: 12,
    title: "Seguridad Informática",
    instructor: "Marcus Johnson",
    image: "https://th.bing.com/th/id/R.d3d80093e490e8af8722478e4a5d5d5f?rik=8iUmdnyDoIvKfQ&pid=ImgRaw&r=0",
    price: 80,
    level: "Avanzado",
    duration: "6 semanas",
    description: "Aprende sobre amenazas de seguridad informática, técnicas de hacking ético y medidas de protección.",
  },
];
